### ISSUE TITLE
Force a language

### ISSUE THREAD

**Issue by tversteeg** [simeg/commentective#19]
It happens sometimes where you want to check the comments for a file with a non-standard extension. It would be nice if you could still force the language for such a file.

For example:

```bash
./commentective file.weird_ext --lang=cpp
```

**Comment by simeg** [comment]
Great idea! Will add this in the next version.

**Comment by simeg** [comment]
See #23.

**Comment by tversteeg** [comment]
Where is the fix for this? Is that the `--extension` flag?

**Comment by simeg** [comment]
@tversteeg Yes, exactly. I considered using `--lang` but I think it's unambiguous because languages could be spelled differently, like `cpp` and `c++`. With `--extension` there's less of a chance to get it wrong. Some languages support multiple extensions but most don't.

**Comment by tversteeg** [comment]
Oh but I don't think that's what I meant, I meant a way to force a file to always use a specific language. For example when I have a `.h` file and I want to force it to be parsed like a Python file (for some weird reason).

**Comment by simeg** [comment]
Oh, haha :) Sure, that feature could be useful too. I'll add it to my list of flags/options I keep in #16.
